### ISSUE TITLE
能推荐一个 text style transform 模型吗？

### ISSUE THREAD

**Issue by linonetwo** [Franceshe/awesome-generative-models#1]
我主要是用规则方法的，对神经网络没怎么关注过，问下你有没有看过把文本转换为同义文本的项目或者模型？

我在做 https://github.com/linonetwo/chatting-question-generation 玩，根据之前做 https://github.com/linonetwo/communism-report-generator 的经验，纯规则方法生成的结果会比较死板，可能用 style transform 可以解决。

**Comment by Franceshe** [comment]
@linonetwo 
比较经典的方法啊是使用"word2vec"做words similarity的baseline 基准测试。
相比目前比较流行的其他transfomer models, like GPT3, Bert，word2vec 主要是利用神经网络学习words similarity in vector space, 虽然涉及word embeddings, 但并不涉及contexual words embeddings, 而且参数少，更容易训练。
关于word2vec的理论知识stanford cs224n NLP 前几节课有很好的介绍
Implement 的话，tensorflow 有一些关于word2vec 的代码适用案例

类似于你的question generation 项目，有一个好玩的项目叫AI Dungeon，它一开始是使用了gpt2 微调+自己收集的冒险故事text + ctrl（for conditional generation） model 的 一个地下城故事生成器。 

comment by 低多边形厌氧菌:
"AI Dungeon之所以值得关注，是因为它展示了机器学习产生的文本叙事的内容是能够受到外部信号的控制的。只不过它现在考虑的外部控制信号还过于简单不能承载稍有点复杂的故事逻辑。只要它能够引入上述“故事表示工程学”，我认为有可能产生非常厉害的故事创作引擎"

Reference:
1. [word2vec wiki](https://en.wikipedia.org/wiki/Word2vec)
2. [stanford cs224n](https://web.stanford.edu/class/cs224n/readings/cs224n-2019-notes01-wordvecs1.pdf)
3. [Tensorflow word2vec implementation](https://www.tensorflow.org/tutorials/text/word2vec)
4. [AI Dungeon](https://github.com/Latitude-Archives/AIDungeon)
5. [低多边形厌氧菌:故事工程学：人工智能和交互式叙事](https://indienova.com/indie-game-development/narrative-engineer-ai-and-storyteller/)

**Comment by linonetwo** [comment]
哈哈 感谢啊，我工作之余学习一下，毕业之后就会陷入老砍柴不磨刀的困境，得搞点这种小玩意来跳出去。

word2vec应该是用于寻找同义词的吧，那我应该是先用 https://github.com/linonetwo/segmentit 分词，然后随机对于部分词（比如词性是形容词的部分）做同义词替换？

第一阶段我先这么搞看看。
